# Generated by Django 5.2.1 on 2025-06-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('RENTER', 'Renter'), ('LENDER', 'Lender'), ('ADMIN', 'Admin')], default='RENTER', max_length=10),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
